org: flowper
service: aws-lambda-send-email

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    OAUTH_CLIENT_ID: ${env:OAUTH_CLIENT_ID}
    OAUTH_CLIENT_SECRET: ${env:OAUTH_CLIENT_SECRET}
    OAUTH_REDIRECT_URI: ${env:OAUTH_REDIRECT_URI}
    OAUTH_REFRESH_TOKEN: ${env:OAUTH_REFRESH_TOKEN}
    MAIL_FROM: ${env:MAIL_FROM}

functions:
  sendConfirmationEmail:
    handler: src/mail.sendConfirmationEmail
    events:
      - http:
          cors: true
          private: true
          path: /send-mail
          method: post
